# Generated by Django 6.1 on 2026-08-20 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adressage', '0001_initial'),
        ('users', '0002_commercant_client_livreur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('canal', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('FACEBOOK', 'Facebook'), ('TIKTOK', 'TikTok'), ('MANUEL', 'Manuel')], max_length=20)),
                ('statut', models.CharField(choices=[('NOUVELLE', 'Nouvelle'), ('VALIDEE', 'Validée'), ('ASSIGNEE', 'Assignée'), ('EN_LIVRAISON', 'En livraison'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée')], default='NOUVELLE', max_length=20)),
                ('frais_livraison', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adresse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commande', to='adressage.adressedigitale')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='users.client')),
                ('commercant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='users.commercant')),
                ('livreur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='users.livreur')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('NOUVELLE', 'Nouvelle'), ('VALIDEE', 'Validée'), ('ASSIGNEE', 'Assignée'), ('EN_LIVRAISON', 'En livraison'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée')], max_length=20)),
                ('commentaire', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='commandes.commande')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.CharField(max_length=200)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=0, max_digits=10)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='commandes.commande')),
            ],
        ),
    ]
