# Generated by Django 6.1 on 2026-08-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdresseDigitale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quartier', models.CharField(max_length=150)),
                ('indications_reperes', models.TextField(blank=True)),
                ('photo_repere', models.ImageField(blank=True, null=True, upload_to='reperes/')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30, unique=True)),
                ('canal', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('MANUEL', 'Manuel')], max_length=20)),
                ('statut', models.CharField(choices=[('NOUVELLE', 'Nouvelle'), ('VALIDEE', 'Validée'), ('ASSIGNEE', 'Assignée'), ('EN_LIVRAISON', 'En livraison'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée'), ('ECHEC', 'Échec')], default='NOUVELLE', max_length=20)),
                ('mode_paiement', models.CharField(choices=[('IMMEDIAT', 'Payé immédiatement'), ('A_LA_LIVRAISON', 'Paiement à la livraison')], default='A_LA_LIVRAISON', max_length=20)),
                ('frais_livraison', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(max_length=20)),
                ('commentaire', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.CharField(max_length=150)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
