# Generated by Django 6.1 on 2026-09-04 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0002_initial'),
        ('commandes', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanalConnecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram')], max_length=20)),
                ('identifiant_externe', models.CharField(blank=True, max_length=255)),
                ('token_acces', models.CharField(blank=True, max_length=500)),
                ('statut_connexion', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONNECTE', 'Connecté'), ('ERREUR', 'Erreur')], default='EN_ATTENTE', max_length=20)),
                ('connecte_le', models.DateTimeField(blank=True, null=True)),
                ('commercant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canaux', to='users.commercant')),
            ],
            options={
                'unique_together': {('commercant', 'type')},
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_identifiant_externe', models.CharField(max_length=255)),
                ('etat', models.CharField(choices=[('DEBUT', 'Début'), ('CATALOGUE_ENVOYE', 'Catalogue envoyé'), ('PANIER_EN_COURS', 'Panier en cours'), ('EN_ATTENTE_ADRESSE', "En attente d'adresse"), ('COMMANDE_CREEE', 'Commande créée')], default='DEBUT', max_length=30)),
                ('quartier_temp', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='canaux.canalconnecte')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.client')),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commandes.commande')),
                ('commercant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='users.commercant')),
            ],
            options={
                'unique_together': {('canal', 'client_identifiant_externe')},
            },
        ),
        migrations.CreateModel(
            name='PanierItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panier', to='canaux.conversation')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.produit')),
            ],
        ),
    ]
