# Generated by Django 6.1 on 2026-09-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canaux', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='etat',
            field=models.CharField(choices=[('DEBUT', 'Début'), ('MENU', 'Menu principal'), ('CATALOGUE', 'Catalogue affiché'), ('CATALOGUE_ENVOYE', 'Catalogue envoyé'), ('PANIER_EN_COURS', 'Panier en cours'), ('EN_ATTENTE_ADRESSE', "En attente d'adresse"), ('COMMANDE_CREEE', 'Commande créée')], default='DEBUT', max_length=30),
        ),
    ]
