# Generated by Django 6.1 on 2026-09-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canaux", "0002_alter_conversation_etat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="etat",
            field=models.CharField(
                choices=[
                    ("DEBUT", "Début"),
                    ("EN_ATTENTE_NOM", "En attente du nom"),
                    ("EN_ATTENTE_CONTACT", "En attente du contact"),
                    ("MENU", "Menu principal"),
                    ("CATALOGUE", "Catalogue affiché"),
                    ("CATALOGUE_ENVOYE", "Catalogue envoyé"),
                    ("PANIER_EN_COURS", "Panier en cours"),
                    ("EN_ATTENTE_ADRESSE", "En attente d'adresse"),
                    ("COMMANDE_CREEE", "Commande créée"),
                ],
                default="DEBUT",
                max_length=30,
            ),
        ),
    ]
