# Generated by Django 6.1 on 2026-08-30 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='commercant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='users.commercant'),
        ),
    ]
