# Generated by Django 6.1 on 2026-08-30 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('ASSIGNEE', 'Assignée'), ('ACCEPTEE', 'Acceptée'), ('EN_COURS', 'En cours'), ('LIVREE', 'Livrée'), ('ECHEC', 'Échec')], default='ASSIGNEE', max_length=20)),
                ('date_assignation', models.DateTimeField(auto_now_add=True)),
                ('date_livraison', models.DateTimeField(blank=True, null=True)),
                ('preuve_livraison', models.ImageField(blank=True, null=True, upload_to='preuves/')),
                ('notes', models.TextField(blank=True)),
                ('paiement_recu', models.BooleanField(default=False)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livraison', to='commandes.commande')),
            ],
        ),
    ]
